### ISSUE TITLE
Noticeable delay in Font loading and rendering

### ISSUE THREAD

**Issue by Hypermona** [swaaz/Halo#75]
**Describe the bug**
Whenever I open or reload this app I noticed a 500ms delay in rendering font-family

**To Reproduce**
1. Go to 'home'
2. Click on 'reload'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swaaz** [comment]
Great work!! 🔥  @Hypermona I think I have deployed the optimized build now. Do check it out and let us know if there are any other bugs. Once you think this bug is solved then feel free to close the issue.

**Comment by suhanacharya** [comment]
@swaaz I think we need to use 'preload' to optimize for first-time user font loading.
Reference: 
https://web.dev/preload-optional-fonts/

**Comment by Hypermona** [comment]
Now it is perfect🔥
